### ISSUE TITLE
can u build tensorflow 1.3 with and without GPU for Python 2.7?

### ISSUE THREAD

**Issue by diwu1989** [bodak/tensorflow-wheels#2]
thanks

for CPU, can u enable the AVX extension that the macbook retina has?

**Comment by bodak** [comment]
Done. AVX SSE4.1 and SSE4.2 should be enabled for all. Let me know if not.
https://github.com/bodak/tensorflow-wheels/releases/tag/1.3.0

Unfortunately, Tensorflow dropped support for Mac GPUs past v1.1, so can't build v1.3 reliably.

**Comment by diwu1989** [comment]
yeah, i recognized that too, too bad about losing the GPU support, but having decent CPU acceleration helps too, thanks!
