### ISSUE TITLE
TF 1.5 OSX Sierra Python 2.7 CPU

### ISSUE THREAD

**Issue by eggie5** [bodak/tensorflow-wheels#3]
Can you get me a build for TF 1.5 OSX Sierra Python 2.7 CPU? 

Also, on your 1.4 build I still get this warning: 

```
I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
```

But otherwise compared to the unoptimzed build I do get 1 image/sec high throughput on VGG.

**Comment by bodak** [comment]
I just added 1.5 for Python 3.6. Also **managed to do it for GPU** after some tinkering.

I will try to do 2.7 builds over the weekend, but I don't use 2.7 anymore for any projects. 

Regarding the warning: you probably have a more recent CPU that supports those instructions. The I7-3615QM does not.

**Comment by bodak** [comment]
https://github.com/bodak/tensorflow-wheels/releases/tag/1.5.0_py27
