### ISSUE TITLE
tf 1.6.0 release?

### ISSUE THREAD

**Issue by nextofsearch** [bodak/tensorflow-wheels#4]
Hi @bodak 

Thank you so much for the wheels. Do you have one with tf 1.6.0, not 1.6.0 rc1? If you can share how you compile it, I would tremendously appreciate it. So many people have tried to compile it but none buy you made it.

Thank you again.

**Comment by nextofsearch** [comment]
I realized the wheel of tf 1.6.0 is CPU version, not GPU version. Still can you share how you compiled the tf GPU version on mac? Thanks,

**Comment by bodak** [comment]
There are quite a few gists out there detailing compiling TF1.6 GPU on Macs. Linked one below.

https://gist.github.com/mattiasarro/1f3498a26ad111a8d99199eaf64551be
