### ISSUE TITLE
CUDA 9.0 or 9.1 with Tensorflow 1.5.0 GPU Mac Python 3.6 (rMBP m2012)

### ISSUE THREAD

**Issue by nextofsearch** [bodak/tensorflow-wheels#5]
Hi,

You stated that you used CUDA 9.1 with Tensorflow 1.5.0 GPU Mac Python 3.6 (rMBP m2012) release. But when I import tensorflow, it seeks libcublas.9.0.dylib. I'm wondering if you used CUDA9.0 with the release.

`Library not loaded: @rpath/libcublas.9.0.dylib`

**Comment by bodak** [comment]
It probably was 9.0. Thanks for pointing out.
